name: Build App
on: [push]
jobs:
    build-react-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - name: Install dependencies
              run: npm i
            - name: Build app
              run: npm run build
            - name: Done
              run: echo "Horray!!!"
